# SPDX-FileCopyrightText: The fastMethyl authors
# SPDX-License-Identifier: Artistic-2.0
#
# Licensing for files that do not carry an inline SPDX header (DCF/config files
# and the test files ported from minfi). Files that already have inline headers
# get the same license via precedence = "aggregate" (no conflict).

version = 1

[[annotations]]
path = ["DESCRIPTION", ".Rbuildignore", ".gitignore", ".ilo.rc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The fastMethyl authors"
SPDX-License-Identifier = "Artistic-2.0"

[[annotations]]
path = ["tests/testthat/**", "man/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The fastMethyl authors"
SPDX-License-Identifier = "Artistic-2.0"
